theme = "tokyonight"

[editor]
mouse = false
line-number = "relative"
cursorline = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.lsp]
display-inlay-hints = true

[keys.normal]
# A -> (left) option
# If using iTerm2, make sure to set (left) option as meta key in Profiles->Keys
# C -> control
"esc" = ["collapse_selection", "keep_primary_selection"]
# Move line up/down using A-k, A-j
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before"
]
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before"
]
